/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otgservice;

import java.awt.Frame;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Andy
 */
public class FramePilihTeknisi extends javax.swing.JFrame {

    /**
     * Creates new form FramePilihTeknisi
     */
    String kode;
    String kota="";
    ArrayList<ClassPilihTeknisi> teknisi = new ArrayList<ClassPilihTeknisi>();
    public static BufferedImage image;
    public static BufferedImage foto;
    public static Frame isidatabooking;
    public static String kodetek;
    public FramePilihTeknisi() {
        initComponents();
        cbkota.removeAllItems();
        String SQL = "SELECT DISTINCT KOTA FROM TEKNISI";
        ResultSet rs = OTGService.executeQuery(SQL);

        try {
            while(rs.next()) {
                String cekkota = rs.getString(1);
                cbkota.addItem(cekkota);
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbjenis = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbnama = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbkota = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tbalamat = new javax.swing.JTextField();
        tbtelp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fotoPilihTeknisi1 = new otgservice.FotoPilihTeknisi();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Frame Pilih Teknisi");

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Komputer", "Motor", "Mobil", "Mesin" }));
        cbjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjenisActionPerformed(evt);
            }
        });

        jLabel2.setText("Jenis Service");

        jLabel3.setText("Daftar Nama Teknisi");

        cbnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnamaActionPerformed(evt);
            }
        });

        jLabel4.setText("Kota");

        cbkota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkotaActionPerformed(evt);
            }
        });

        jLabel5.setText("ALamat");

        jLabel6.setText("Notelp");

        jLabel7.setText("Foto");

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fotoPilihTeknisi1Layout = new javax.swing.GroupLayout(fotoPilihTeknisi1);
        fotoPilihTeknisi1.setLayout(fotoPilihTeknisi1Layout);
        fotoPilihTeknisi1Layout.setHorizontalGroup(
            fotoPilihTeknisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        fotoPilihTeknisi1Layout.setVerticalGroup(
            fotoPilihTeknisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbnama, 0, 300, Short.MAX_VALUE)
                            .addComponent(cbkota, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbalamat)
                            .addComponent(cbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tbtelp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(fotoPilihTeknisi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tbalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tbtelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7)
                    .addComponent(fotoPilihTeknisi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjenisActionPerformed
        // TODO add your handling code here:
        image = null;
        if (cbjenis.getSelectedItem().toString().equals("Komputer")){
            kode = "TKO";
        }
        else if (cbjenis.getSelectedItem().toString().equals("Motor")){
            kode = "TMT";
        }
        else if (cbjenis.getSelectedItem().toString().equals("Mobil")){
            kode = "TMB";
        }
        else if (cbjenis.getSelectedItem().toString().equals("Mesin")){
            kode = "TME";
        }
        
        cbnama.removeAllItems();
        String SQL = "SELECT KODETEKNISI, NAMATEKNISI, ALAMAT, NOTELP, FOTOPRIBADI FROM TEKNISI WHERE KODETEKNISI LIKE '" + kode + "%' AND KOTA LIKE '%" + kota + "%'";
        ResultSet rs = OTGService.executeQuery(SQL);

        try {
            while(rs.next()) {
                String kodetek = rs.getString(1);
                String nama = rs.getString(2);
                String alamat = rs.getString(3);
                String telp = rs.getString(4);
                Blob foto = rs.getBlob(5);
                InputStream in = foto.getBinaryStream();
                try {
                    image = ImageIO.read(in);
                } catch (IOException ex) {
                    Logger.getLogger(FramePilihTeknisi.class.getName()).log(Level.SEVERE, null, ex);
                }
                teknisi.add(new ClassPilihTeknisi(kodetek, nama, alamat, telp, image));
                cbnama.addItem(teknisi.get(teknisi.size()-1).getNama());
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbjenisActionPerformed

    private void cbkotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkotaActionPerformed
        // TODO add your handling code here:
        image = null;
        cbnama.removeAllItems();
        kota = cbkota.getSelectedItem().toString();
        String SQL = "SELECT KODETEKNISI, NAMATEKNISI, ALAMAT, NOTELP, FOTOPRIBADI FROM TEKNISI WHERE KODETEKNISI LIKE '" + kode + "%' AND KOTA LIKE '%" + kota + "%'";
        ResultSet rs = OTGService.executeQuery(SQL);

        try {
            while(rs.next()) {
                String kodetek = rs.getString(1);
                String nama = rs.getString(2);
                String alamat = rs.getString(3);
                String telp = rs.getString(4);
                Blob foto = rs.getBlob(5);
                InputStream in = foto.getBinaryStream();
                try {
                    image = ImageIO.read(in);
                } catch (IOException ex) {
                    Logger.getLogger(FramePilihTeknisi.class.getName()).log(Level.SEVERE, null, ex);
                }
                teknisi.add(new ClassPilihTeknisi(kodetek, nama, alamat, telp, image));
                cbnama.addItem(teknisi.get(teknisi.size()-1).getNama());
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbkotaActionPerformed

    private void cbnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnamaActionPerformed
        // TODO add your handling code here:
        foto = null;
        tbalamat.setText("");
        tbtelp.setText("");
        for (int i = 0; i < teknisi.size(); i++) {
            if (cbnama.getItemCount()>0){
                if (cbnama.getSelectedItem().equals(teknisi.get(i).getNama())){
                    foto = teknisi.get(i).getFoto();
                    tbalamat.setText(teknisi.get(i).getAlamat());
                    tbtelp.setText(teknisi.get(i).getTelp());
                    kodetek = teknisi.get(i).getKode();
                }
            }
        }
    }//GEN-LAST:event_cbnamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        isidatabooking = new IsiDataBooking();
        isidatabooking.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MainMenu.f2.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePilihTeknisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePilihTeknisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePilihTeknisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePilihTeknisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePilihTeknisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JComboBox<String> cbkota;
    private javax.swing.JComboBox<String> cbnama;
    private otgservice.FotoPilihTeknisi fotoPilihTeknisi1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tbalamat;
    private javax.swing.JTextField tbtelp;
    // End of variables declaration//GEN-END:variables
}
